### ISSUE TITLE
No "vendor" directory?

### ISSUE THREAD

**Issue by codewithfeeling** [andrewelkins/Laravel-4-Bootstrap#13]
I cloned your project, but the `artisan` commands wouldn't work, and trying to navigate to the web root gave this error:

Warning: require(/Library/WebServer/Documents/laravel-bootstrap/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /Library/WebServer/Documents/laravel-bootstrap/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/Library/WebServer/Documents/laravel-bootstrap/bootstrap/../vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php5.4.10/lib/php') in /Library/WebServer/Documents/laravel-bootstrap/bootstrap/autoload.php on line 17

Sure enough, looking in the root directory, I don't see `vendor` at all.

Just wondered if I'm missing something obvious?

**Comment by andrew13** [comment]
Did you follow the install steps? You need to run composer.

**Comment by codewithfeeling** [comment]
Eek. Sorry. Missed the `composer install` command. All sweet now. Thanks.

**Comment by jjrobinson** [comment]
why the heck isn't that part of laravel to start with if you have to run it no matter what on every new laravel project?

**Comment by andrew13** [comment]
You can add to it, packages can be updated,  dependencies are taken care
of. Lots of reasons.

**Comment by TuanTranDev** [comment]
thank you so much. i have just run "composer install" to fix a problem like this.
