### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by brunocascio** [andrewelkins/Laravel-4-Bootstrap#18]
If there is more than one notification of a type (eg error), an exception is triggered

**Comment by brunocascio** [comment]
Solution:

@if ( is_array($message) )
          @foreach ( $message as $m )
            {{{ $m }}}
          @endforeach
@else
          {{{ $message }}}
@endif

**Comment by andrew13** [comment]
Merged a fix for this. Thanks!

**Comment by brunocascio** [comment]
Your welcome! Thanks!
