### ISSUE TITLE
Problems using artisan

### ISSUE THREAD

**Issue by vcardins** [andrewelkins/Laravel-4-Bootstrap#2]
Hello, was having issues when tried to run any artisan command. The error was:
exception 'ReflectionException' with message 'Class path.public does not exist' in C:\Winginx\home\momentum\vendor\laravel\framework\src\Illuminate\Container\Container.php:274

After analyzing and comparing files, I realized that it was a missing config, i added the following line to start.php file:

[code]$app->instance('path.public', $appPath = **DIR**.'/public');[/code]

**Comment by andrew13** [comment]
Thanks, updated start
