### ISSUE TITLE
Artisan migrate error

### ISSUE THREAD

**Issue by sawant** [andrewelkins/Laravel-4-Bootstrap#8]
1. Cloned from git.
2. CD into directory
3. Installed dependencies with "composer install"
4. Edited app/config/database.php with DB info
5. Executed "php artisan migrate" ... it generates the following error:

{"error":{"type":"ErrorException","message":"Undefined index: driver","file":"\/Path_To_laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Mail\/MailServiceProvider.php","line":79}}

System: Mac, OS X Mountain Lion 10.8.3. PHP v 5.4.10.

**Comment by andrew13** [comment]
Thanks for the report!

**Comment by kostas123** [comment]
Hi , 
I've got the same error , made the installation on a Windows 7 machine . 

$ php artisan migrate
{"error":{"type":"ErrorException","message":"Undefined index: driver","file":"C:\wamp\www\l4bootst
rapauth\vendor\laravel\framework\src\Illuminate\Mail\MailServiceProvider.php","line":79}}DimDev@DIMDEV-
PC /C/wamp/www/sublime/l4bootstrapauth (master)

**Comment by andrew13** [comment]
I'll check this. I need to update the app anyway.

**Comment by andrew13** [comment]
Updated the repo. Should be good to go now.
