### ISSUE TITLE
CSRF  vulnerability 

### ISSUE THREAD

**Issue by kostas123** [andrewelkins/Laravel-4-Bootstrap#9]
Hi , 
A beforeFilter is defined  with  a "csrf" filter in the constructor of  BaseController . AuthorizedController (which extends the BaseController) has also a constructor defined .  
Parent constructors are not called implicitly if the child class defines a constructor. , so the "csrf" filter will never be executed  . 
AuthorizedController should explicitly call his parent's constructor (parent::__construct())
Reference on php.net : http://php.net/manual/en/language.oop5.decon.php . 
Kind regards ,

**Comment by andrew13** [comment]
Thanks for catching that oversight!
